.github/workflows/main.yml, gateware/src/example_dsp/sim_dsp_core.cpp, gateware/src/example_dsp/top.py, gateware/src/tiliqua/dsp.py, gateware/src/tiliqua/eurorack_pmod.py, gateware/src/tiliqua/midi.py, gateware/src/tiliqua/sim.py, gateware/src/tiliqua/tiliqua_platform.py, gateware/src/vendor/serial.py
* implement a simple library for decoding binary midi streams
* add an example bitstream that converts serial midi into CV signals on the tiliqua outputs
=> gateware/midi: add a simple midi library and `midicv` example

gateware/src/example_soc/fw/Cargo.lock, gateware/src/example_soc/fw/Cargo.toml, gateware/src/example_soc/fw/src/i2c.rs, gateware/src/example_soc/fw/src/lib.rs, gateware/src/example_soc/fw/src/main.rs, gateware/src/example_soc/top.py, gateware/src/tiliqua/i2c.py, gateware/src/vendor/i2c.py, gateware/tests/test_i2c.py
Tiliqua R2 has a few I2C peripherals, so we need an I2C core that can be driven by the SoC. This one is largely based on the `transaction()` semantics from rust `embedded-hal` v1.0.0 - the exact semantics are added to the core documentation.
=> gateware/i2c: implement i2c peripheral, integrate in `example_soc`

gateware/src/example_vectorscope/top.py, gateware/src/selftest/fw/src/main.rs, gateware/src/selftest/top.py, gateware/src/tiliqua/raster.py, gateware/src/tiliqua/tiliqua_platform.py, gateware/src/tiliqua/video.py, gateware/src/vendor/dvi/dvi_generator.sv, gateware/src/xbeam/fw/src/main.rs, gateware/src/xbeam/top.py
* Rewrite timing generator to adhere to DVI spec
* Set default resolution to 1280x720p60
* Increase drive and slew, 8mA is still <10mA (spec) but we don't want to get too hot.
* Extra registers in TMDS serializer to improve timing
=> Improve video timings, set default to 1280x720p60

gateware/src/poly/fw/Cargo.lock, gateware/src/poly/fw/src/lib.rs, gateware/src/poly/fw/src/main.rs, gateware/src/poly/fw/src/opts.rs, gateware/src/rs/hal/src/lib.rs, gateware/src/rs/hal/src/video.rs, gateware/src/rs/lib/Cargo.toml, gateware/src/rs/lib/src/lib.rs, gateware/src/rs/lib/src/palette.rs, gateware/src/tiliqua/tiliqua_soc.py, gateware/src/tiliqua/video.py, gateware/src/xbeam/fw/Cargo.lock, gateware/src/xbeam/fw/Cargo.toml, gateware/src/xbeam/fw/src/lib.rs, gateware/src/xbeam/fw/src/main.rs, gateware/src/xbeam/fw/src/opts.rs
* expose palette memory that decodes pixels from RAM into screen colors
* allow the palette memory to be tweaked by the SoC
* add a menu option to change the palette to xbeam and poly
* start with linear, exponential, grayscale and inverted palettes
=> poly/xbeam: add color palette selection

gateware/src/boot/fw/Cargo.toml, gateware/src/poly/fw/Cargo.toml, gateware/src/poly/fw/src/main.rs, gateware/src/rs/handlers.rs, gateware/src/selftest/fw/Cargo.toml, gateware/src/tiliqua/tiliqua_soc.py, gateware/src/tiliqua/video.py, gateware/src/vendor/soc/cpu/verilog/vexriscv/scala/build.sbt, gateware/src/vendor/soc/cpu/verilog/vexriscv/scala/src/main/scala/GenCoreCynthion.scala, gateware/src/vendor/soc/cpu/verilog/vexriscv/vexriscv_cynthion.v, gateware/src/vendor/soc/cpu/verilog/vexriscv/vexriscv_cynthion.yaml, gateware/src/xbeam/fw/Cargo.toml
* fix vexriscv sbt build scripts so its easier to modify in-place
* modify vexriscv configuration to remove icache, not necessary for any example bitstreams.
* reduce firmware bloat with cargo flags, and reduce sram size from 64K to 32K.
* remove `pre_main` for now as it seems to break under LTO. interestingly it doesn't seem to be necessary. maybe because icache is gone.
=> gateware/soc: modify vexriscv configuration, reduce fw size

.github/workflows/main.yml, gateware/src/amaranth_future/fixed.py, gateware/src/tiliqua/dsp.py, gateware/src/tiliqua/eurorack_pmod.py, gateware/src/tiliqua/i2c.py, gateware/src/tiliqua/raster.py, gateware/src/tiliqua/scope.py, gateware/src/tiliqua/test_util.py, gateware/src/top/dsp/top.py, gateware/src/top/polysyn/top.py, gateware/src/vendor/i2c.py, gateware/tests/test_dsp.py, gateware/tests/test_i2c.py
* update all unit testbenches to amaranth 0.5, add to CI
* add utilities for testing wishbone transactions against amaranth-soc peripherals (and i2c example)
* switch from `ast` to `hdl` top-level library where possible to squash amaranth 0.5 warnings
* switch i2c implementation from luna to glasgow implementation to squash Record warnings.
=> gateware: update testbenches, squash more amaranth 0.5 warnings.

.github/workflows/main.yml, gateware/pdm.lock, gateware/pyproject.toml, gateware/src/tiliqua/cache.py, gateware/src/tiliqua/delay_line.py, gateware/src/top/dsp/top.py, gateware/tests/test_delayln.py
A bunch of improvements to `DelayLine` & `Cache` to facilitate psram-backed pitch shifting:
- `cache`: reduce memory access port shape to 32-bit always (fix RAM inference)
- `cache`: add switch to select LUTRAM or dual-port RAM as backing store
- `delayline`: fix logic where zero delay is requested
- `test_delayln`: parameterize test cases and add more coverage
- `top/dsp`: modify `pitch` example to be PSRAM-backed with much longer grain size
=> cache/delay_line: improvements for psram-backed pitch shifting

gateware/src/tiliqua/tiliqua_platform.py, gateware/src/tiliqua/tiliqua_pll.py, gateware/src/top/usb_audio/top.py, gateware/src/top/vectorscope_no_soc/top.py
- Re-add hi-res audio PLLs (12.288MHz) on -45k ECP5 platform (default platform)
- Keep using approximate audio PLLs (12.5 MHz) on -25k ECP5 platform (`--sc3` flag)
- Switch USB VID/PID to match https://pid.codes/1209/AA62/
Longer term solution that should work on both platforms: https://github.com/apfelaudio/tiliqua/issues/55
=> pll: add hi-res audio PLLs for LFE5U-45/SC2 platform

gateware/src/tiliqua/dsp.py, gateware/tests/test_dsp.py
- Rewrite and document `dsp.FIR` to reduce LUT usage (use `Memory` primitives instead of `Array`).
- Add a proper validation testbench to compare `dsp.FIR` performance against scipy.
=> dsp/fir: rewrite to reduce LUT usage

gateware/src/tiliqua/dsp.py, gateware/tests/test_dsp.py
- Add optimization to `FIR` implementation so you can use the 'stride' argument to avoid performing MACs or needing tap storage for samples that are expected to always be zero.
- Update `Resample` to use this field, meaning it is now a polyphase resampler.
- Add some test cases comparing `Resample` and `FIR` outputs to `scipy.signal` outputs.
- TODO: `n_up` (numerators) must currently be a power of 2, however it should not be so hard to remove this restriction (useful for some common audio ratios e.g 44100 / 48000).
=> dsp: implement polyphase resampler

gateware/src/rs/hal/src/polysynth.rs, gateware/src/rs/lib/src/leds.rs, gateware/src/tiliqua/dsp.py, gateware/src/tiliqua/midi.py, gateware/src/top/polysyn/fw/Cargo.lock, gateware/src/top/polysyn/fw/Cargo.toml, gateware/src/top/polysyn/fw/src/main.rs, gateware/src/top/polysyn/fw/src/opts.rs, gateware/src/top/polysyn/top.py, gateware/tests/test_midi.py
Rewrite `MidiVoiceTracker` and update `Polysyn` example to use it. Main items:
- TRS MIDI pitch bend + mod wheel now fully supported.
- Much improved voice culling and replacement algorithm.
- Implement MIDI polyphonic pressure messages and all stop (used by touch interface but theoretically controllable through TRS MIDI as well..)
- TRS MIDI input and touch inputs can be used simultaneously (you can touch while pitch bending on a control surface, or play bass notes one the touchjack interface and melody on a keyboard simultaneously etc.)
- Touchjack control messages / notes are routed through the SoC (so we can easily change notes in the menu system in the future, or dynamically based on MIDI inputs)
- Tiliqua TRS MIDI activity LED now actually lights up when there is MIDI traffic.
- …
=> midi/polysyn: rewrite MidiVoiceTracker, various improvements

.github/workflows/main.yml, gateware/docs/top.rst, gateware/pyproject.toml, gateware/src/tiliqua/midi.py, gateware/src/tiliqua/usb_host.py, gateware/src/top/dsp/top.py, gateware/src/top/usb_host/top.py, gateware/src/vendor/ila.py, gateware/tests/test_midi.py, gateware/tests/test_usb.py
* Extremely bare-bones USB host logic intended for using Tiliqua as a USB MIDI host, initially as a MIDI/CV converter.
* Built by wiring together a lot of existing LUNA components out-of-tree and adding some things (SOF/token generation, host reset and setup phase logic).
* Intended solely for hardware validation at the moment, still requires extensive testing across different MIDI devices as well as automatically reading the descriptors to select the correct interface.
* Some unrelated improvements:
* Fix ILA timestamping
* Move MidiCV logic to common `midi.py` library and remove deprecated Amaranth constructs.
=> usb/host: add basic USB MIDI host implementation and demo

gateware/src/tiliqua/sim.py, gateware/src/tiliqua/tiliqua_platform.py, gateware/src/tiliqua/tiliqua_soc.py, gateware/src/top/selftest/fw/src/main.rs, gateware/src/vendor/soc/cores/spiflash/__init__.py, gateware/src/vendor/soc/cores/spiflash/controller.py, gateware/src/vendor/soc/cores/spiflash/mmap.py, gateware/src/vendor/soc/cores/spiflash/phy.py, gateware/src/vendor/soc/cores/spiflash/port.py, gateware/src/vendor/soc/cores/spiflash/utils.py
* Add memory-mapped SPI flash support (from `luna-soc`)
* Add a simple test/benchmark to `selftest` bitstream.
* Some changes to `ECP5ConfigurationFlashProvider` to have the pin interfaces still function in simulation.
=> tiliqua_soc: add support for memory-mapped SPI flash

gateware/src/rs/hal/src/i2c.rs, gateware/src/rs/lib/src/ui.rs, gateware/src/tiliqua/eurorack_pmod.py, gateware/src/tiliqua/eurorack_pmod_peripheral.py, gateware/src/tiliqua/i2c.py, gateware/src/tiliqua/tiliqua_platform.py, gateware/src/tiliqua/tiliqua_soc.py, gateware/src/top/bootloader/fw/src/main.rs, gateware/src/top/dsp/top.py, gateware/src/top/selftest/fw/src/main.rs, gateware/src/top/usb_audio/top.py, gateware/src/top/usb_host/top.py, gateware/src/top/vectorscope_no_soc/top.py, gateware/src/vendor/i2c.py, gateware/tests/test_i2c.py
- WARN: the TOUCH IC config is no longer flashed by every bitstream. It's now assumed it was already flashed at the factory (or by a sane previous bitstream). This was removed both to save logic and to allow for pop-free bitstream switching (reflashing the touch IC sometimes resets the codec, maybe due to a power dip).
- Split up `i2c.Peripheral` and `i2c.Streamer`, so the transaction-based I2C core can be used more easily by RTL directly.
- Rewrite the old `eurorack-pmod` state machine in Amaranth based on this new interface.
- This is used for codec, touch init, jack reading, etc
- Resource usage is almost the same as it used to be.
- Crucially, this enables codec muting (pop-free bitstream switching), but is disabled for now.
- Persistent PDN clocking is now enabled on mobo R3+ …
=> tiliqua/i2c: rewrite audio interface i2c state machine

gateware/src/rs/hal/src/polysynth.rs, gateware/src/tiliqua/usb_host.py, gateware/src/top/polysyn/fw/src/main.rs, gateware/src/top/polysyn/fw/src/opts.rs, gateware/src/top/polysyn/top.py
- Add USB screen to `polysyn` menu for enabling MIDI HOST (disconnects TRS MIDI if enabled)
- Correct config ID and endpoint ID can be set in menu, but must currently be manually checked (and set) by looking at the USB device descriptor (e.g. using `lsusb`).
=>  polysyn: add optional USB MIDI host

gateware/docs/bootloader.rst, gateware/docs/gettingstarted.rst, gateware/src/tiliqua/flash.py
- Modify `pdm flash` command to have `archive` and `status` subcommands.
- Now, `pdm flash archive <bitstream.tar.gz>` is used for flashing bitstreams to Tiliqua slots.
- A new `pdm flash status` command is added for dumping the contents of each manifest in every slot (to see what's currently programmed to the Tiliqua).
- An example execution:
=> bootloader/flash: add 'status' command for dumping manifest status

gateware/src/rs/lib/src/ui.rs, gateware/src/top/bootloader/fw/src/main.rs, gateware/src/top/bootloader/fw/src/opts.rs, gateware/src/top/macro_osc/fw/src/main.rs, gateware/src/top/macro_osc/fw/src/opts.rs, gateware/src/top/polysyn/fw/src/main.rs, gateware/src/top/polysyn/fw/src/opts.rs, gateware/src/top/selftest/fw/src/main.rs, gateware/src/top/selftest/fw/src/opts.rs, gateware/src/top/sid/fw/src/main.rs, gateware/src/top/sid/fw/src/opts.rs, gateware/src/top/xbeam/fw/src/main.rs, gateware/src/top/xbeam/fw/src/opts.rs
The shared UI implementation did not need to live in a macro. Switch it out for ordinary generics, making it possible to use in unit tests more easily.
=> rs/ui: remove macro usage from ui::UI

gateware/docs/hardware.rst, gateware/src/rs/hal/src/pmod.rs, gateware/src/tiliqua/eurorack_pmod.py, gateware/src/tiliqua/eurorack_pmod_peripheral.py, gateware/src/top/bootloader/fw/src/main.rs
From https://github.com/apfaudio/tiliqua/issues/81:
```
After some probing, turns out this is a hardware artifact (!!) related to the soft-mute circuit. When a DVI sink (i.e a display) has its 3.3V terminations enabled (usually only a few seconds after an active display connection), it may back-power the Tiliqua through the 50R (sink) + 220R (tiliqua) series resistors into the ECP5. According to the ECP5 datasheet, this is permissible (even if the ECP5 is off). So it should not damage the hardware at least.
The consequence is we see ~1V on the 3.3V rail in this specific scenario, even if the Tiliqua is off. This means the soft-mute circuit never fully deasserts the PDN pin to the audio CODEC when the Tiliqua is powered off, which is required to initialize the CODEC correctly.
```
As a …
=> bootloader: add mitigation for DVI leakage current (issue #81)

gateware/docs/bootloader.rst, gateware/docs/gettingstarted.rst, gateware/src/tiliqua/flash.py, gateware/src/top/bootloader/fw/src/main.rs
A few changes so that `pdm flash archive` and `pdm flash status` don't cause audio pops when run from the `bootloader` bitstream.
- Always mute audio codec from `bootloader bitstream`
- Always issue `openFPGALoader` commands with `--skip-reset` on all but the last command
- Rewrite `flash.py` so it's a bit more maintainable
- Add some ASCII art showing the SoldierCrab flash layout.
=> bootloader/flasher: pop-free bitstream flashing from bootloader

gateware/src/rs/hal/src/pca9635.rs, gateware/src/tiliqua/eurorack_pmod.py
- Dimming them reduces current consumption and improves v/oct tracking a bit.
=> leds: dim all LEDs to 25%

gateware/src/tiliqua/dma_framebuffer.py, gateware/src/tiliqua/psram_peripheral.py, gateware/src/tiliqua/tiliqua_soc.py, gateware/src/top/macro_osc/fw/src/main.rs, gateware/src/top/selftest/fw/src/main.rs
- Add PSRAM bandwidth monitoring to `selftest` bitstream (total busy %, read % write % and latency overhead %)
- Improve `dma_framebuffer` control logic, now the FIFO only needs to be 1 scanline long as we don't unnecessarily drain it every VSYNC. This reduces DPRAM usage quite a bit.
=> dma_framebuffer/psram_periph: improve framebuffer stability, add CSRs for psram bandwidth monitoring

gateware/src/tiliqua/cache.py, gateware/src/tiliqua/cli.py, gateware/src/tiliqua/dsp.py, gateware/src/tiliqua/eurorack_pmod.py, gateware/src/tiliqua/raster_stroke.py, gateware/src/tiliqua/scope.py, gateware/src/tiliqua/tiliqua_platform.py, gateware/src/tiliqua/usb_audio/__init__.py, gateware/src/tiliqua/usb_audio/audio_to_channels.py, gateware/src/top/macro_osc/fw/src/main.rs, gateware/src/top/macro_osc/fw/src/options.rs, gateware/src/top/macro_osc/top.py, gateware/src/top/polysyn/fw/src/main.rs, gateware/src/top/polysyn/fw/src/options.rs, gateware/src/top/polysyn/top.py, gateware/src/top/sid/top.py, gateware/src/top/usb_audio/top.py, gateware/src/top/vectorscope_no_soc/top.py, gateware/src/top/xbeam/fw/src/main.rs, gateware/src/top/xbeam/fw/src/options.rs, gateware/src/top/xbeam/top.py, gateware/tests/test_i2s.py
This PR makes lots of improvements to `xbeam`, while improving some related topics on the way.
- Feature: Vastly improved backing cache behind `xbeam` plotting, we can plot about 4x as many points as before.
- Drawback: some minor caching artifacts visible, I don't think this is a huge deal, will address in followup. Still looks loads better than before regardless :)
- Feature: `xbeam` now has USB audio support (4ch/4ch 192kHz)
- The audio interface is always present over USB, the menu option just selects whether the audio streams from the USB interface are routed to Tiliqua's jacks or not. This allows instant switching between USB or local analog signals. By default the USB streams are bypassed and are not routed to Tiliqua's inputs/outputs.
- Feature: `xbeam` vectorscope now fully …
=> xbeam/raster/dsp: `xbeam` improvements and bonus cleanup

gateware/src/tiliqua/eurorack_pmod.py, gateware/src/tiliqua/tiliqua_platform.py, gateware/src/top/dsp/top.py
- Fix a pinout error on the R4 motherboard expansion port assignments
- Add support for extra audio boards connected through the PMOD ports
- Add a simple `TripleMirror` demo to `top/dsp` that sends inputs to outputs on 3 audio boards simultaneously (1x internal + 2x external)
=> dsp/eurorack_pmod: add example of external expansion boards

gateware/docs/dsp/cordic.rst, gateware/docs/dsp/fft.rst, gateware/docs/dsp/index.rst, gateware/docs/dsp/types.rst, gateware/scripts/build_bitstreams_no_soc.sh, gateware/src/tiliqua/block.py, gateware/src/tiliqua/complex.py, gateware/src/tiliqua/cordic.py, gateware/src/tiliqua/dsp.py, gateware/src/tiliqua/fft.py, gateware/src/tiliqua/spectral.py, gateware/src/top/dsp/top.py, gateware/tests/test_cordic.py, gateware/tests/test_fft.py
This PR implements loads of new cores required for frequency-domain processing, such as:
- Helpers for block-based processing and streaming complex numbers
- `Block` abstraction for blocks of samples. `CQ` and `Polar` abstractions for complex numbers.
- A resource efficient FFT (same core can do forward an inverse transform, only needs 2 multipliers)
- The `FFT` component, taking complex samples, supporting power-of-2 block sizes.
- Window functions
- The `Window` and `Window.Function` components, currently only `Hann`, `SqrtHann` and `Rect` windows.
- Overlap-add utilities
- The `ComputeOverlappingBlocks` and `OverlapAddBlocks` components, for analyzing / synthesizing audio signals at higher rates than the FFT block size (also used by the STFT components)
- An STFT implementation for …
=> dsp/fft: add cores for frequency-domain processing

gateware/src/rs/hal/src/lib.rs, gateware/src/rs/hal/src/tusb322.rs, gateware/src/tiliqua/usb_audio/__init__.py, gateware/src/top/bootloader/fw/src/main.rs, gateware/src/top/polysyn/fw/src/main.rs, gateware/src/top/polysyn/fw/src/options.rs, gateware/src/top/selftest/fw/src/main.rs, gateware/src/top/xbeam/fw/src/main.rs, gateware/src/top/xbeam/top.py
- It looks like for reliable USB-C enumeration we need to keep the PHY disconnected until we are in `Attached.Snk` state.
- Add a dedicated driver for the TUSB322I USB CC controller and replace all the manual poking of it with driver calls.
- Reset the CC controller in the bootloader to clean up whatever user bitstreams may have done.
=> rs/hal/tusb322: add dedicated driver for tusb322i
